% Solve a Pattern Recognition Problem with a Neural Network
% Script generated by NPRTOOL
%
% This script assumes these variables are defined:
%
%   cancerInputs - input data.
%   cancerTargets - target data.
clear, clc, close all

[inputs,targets] = cancer_dataset;

% inputs = cancerInputs;
% targets = cancerTargets;

% Create a Pattern Recognition Network
hiddenLayerSize = 10;
net = patternnet(hiddenLayerSize);


% Set up Division of Data for Training, Validation, Testing
net.divideParam.trainRatio = 70/100;
net.divideParam.valRatio = 15/100;
net.divideParam.testRatio = 15/100;


% Train the Network
[net,tr] = train(net,inputs,targets);

% Test the Network
outputs = net(inputs);
errors = gsubtract(targets,outputs);
performance = perform(net,targets,outputs)

% View the Network
view(net)

% Plots
% Uncomment these lines to enable various plots.
figure, plotperform(tr)
figure, plottrainstate(tr)
figure, plotconfusion(targets,outputs)
figure, ploterrhist(errors)


% myNet = NeuralNetwork(1, hiddenLayerSize, size(targets, 1), 0.1);
% myNet.train(inputs, 2*targets-1, 'backpropagation');

myNet2 = NeuralNetwork(3, hiddenLayerSize, size(targets, 1), 1e-3);
myNet2.set_functions('sigmoid', 'softmax');
myNet2.train(inputs, targets, 'backpropagation', 0.005);
[error_rate, dout] = myNet2.test(inputs, targets);
figure, plotconfusion(targets,dout)
